language: c++

cache: ccache

git:
  depth: 1

dist: trusty

sudo: true

install:
 - echo "deb http://de.archive.ubuntu.com/ubuntu xenial main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list
 - sudo apt-get update
 - sudo apt-get install --allow-unauthenticated g++ libboost-thread-dev libboost-iostreams-dev libboost-date-time-dev libboost-system-dev libboost-filesystem-dev libboost-program-options-dev libboost-chrono-dev libboost-test-dev libboost-context-dev libboost-regex-dev libboost-locale-dev libboost-signals-dev libboost-coroutine-dev cmake libssl-dev autoconf parallel ccache

addons:
  sonarcloud:
    organization: "flwyiq7go36p6lipr64tbesy5jayad3q"
    token:
      secure: "Ik4xQhs9imtsFIC1SMAPmdLId9lVadY/4PEgo5tM4M5cQRvyt4xeuMMV+CRIT6tGEEqF71ea74qVJTxT7qinWZ3kmHliFjbqDxk1FbjCpK6NGQDyTdfWMVJFIlk7WefvtGAwFBkf6pSTs553bKNNM0HbBYQGKe08waLwv7R+lOmVjTTKIRF/cCVw+C5QQZdXFnUMTg+mRuUqGk4WvNNPmcBfkX0ekHPrXwAD5ATVS1q0iloA0nzHq8CPNmPE+IyXdPw0EBp+fl3cL9MgrlwRbELxrnCKFy+ObdjhDj7z3FDIxDe+03gVlgd+6Fame+9EJCeeeNLF4G4qNR1sLEvHRqVz12/NYnRU9hQL0c/jJtiUquOJA5+HqrhhB9XUZjS1xbHV3aIU5PR0bdDP6MKatvIVwRhwxwhaDXh7VSimis8eL+LvXT7EO+rGjco0c17RuzZpFCsKmXCej4Q8iDBMdOIWwe2WuWi8zb6MFvnLyK2EcM53hAn2yMwU+nprbpHwzU5oJTFZLD+J78zCSGk7uu7vsF+EEnheMwfqafP9MpMEXGXaXZiq7QKy3KvxQTg+1ozPIu+fgxvY0xdyrjJHOSJlrvXN7osjD4IDTs6D5cLAZ04WGIKsulZDr7ZN5n3gmA9h4cfhJsIEia0uQzLmWnfF6RksxWElK1i1+xmse7E="

env:
  global:
    - CCACHE_COMPRESS=exists_means_true
    - CCACHE_MAXSIZE=1Gi
    - CCACHE_SLOPPINESS=include_file_ctime,include_file_mtime,time_macros

script:
 - programs/build_helpers/buildstep -s 3450
 - ccache -s
 - programs/build_helpers/buildstep Prepare 1 "sed -i '/tests/d' libraries/fc/CMakeLists.txt"
 - programs/build_helpers/buildstep cmake 5 "cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_FLAGS=--coverage -DCMAKE_CXX_FLAGS=--coverage -DBoost_USE_STATIC_LIBS=OFF -DCMAKE_CXX_OUTPUT_EXTENSION_REPLACE=ON ."
 - programs/build_helpers/buildstep make.cli_wallet 2600 "programs/build_helpers/make_with_sonar bw-output -j 2 cli_wallet"
 - programs/build_helpers/buildstep make.witness_node 1800 "programs/build_helpers/make_with_sonar bw-output -j 2 witness_node"
 - programs/build_helpers/buildstep make.serializer 20 "programs/build_helpers/make_with_sonar bw-output -j 2 js_operation_serializer"
 - programs/build_helpers/buildstep make.get_dev_key 20 "programs/build_helpers/make_with_sonar bw-output -j 2 get_dev_key"
 - programs/build_helpers/buildstep make.chain_test 1800 "programs/build_helpers/make_with_sonar bw-output -j 2 chain_test"
 - programs/build_helpers/buildstep make.cli_test 1800 "programs/build_helpers/make_with_sonar bw-output -j 2 cli_test"
 - programs/build_helpers/buildstep make.perf_test 1800 "programs/build_helpers/make_with_sonar bw-output -j 2 performance_test"
 - set -o pipefail
 - programs/build_helpers/buildstep run.chain_test 240 "libraries/fc/tests/run-parallel-tests.sh tests/chain_test"
 - programs/build_helpers/buildstep run.cli_test 30 "libraries/fc/tests/run-parallel-tests.sh tests/cli_test"
 - programs/build_helpers/buildstep prepare.sonar 20 'find libraries/[acdenptuw]*/CMakeFiles/*.dir programs/[cdgjsw]*/CMakeFiles/*.dir -type d | while read d; do gcov -o "$d" "${d/CMakeFiles*.dir//}"/*.cpp; done >/dev/null'
 - programs/build_helpers/buildstep run.sonar 1600 "which sonar-scanner && sonar-scanner || true"
 - programs/build_helpers/buildstep end 0
 - ccache -s
