version: '3'
#
# This is a Compose file for OneGram Demo
#

services:
  seed-node-1:
    hostname: og-seed-1
    image: onegram-demo
    build:
      context: .
      dockerfile: Dockerfile.OGC
    ports:
      - 8540:8540
    restart: unless-stopped

  rpc:
    hostname: rpc
    image: onegram-demo
    depends_on:
      - seed-node-1
    command: onegram_witness --seed-node seed-node-1:8540 --rpc-endpoint=0.0.0.0:11011
    ports:
      - 11011:11011
    restart: unless-stopped

  witness-1:
    hostname: og-witness-1
    image: onegram-demo
    depends_on:
      - seed-node-1
    command: onegram_witness --witness-id '"1.6.1"' --seed-node seed-node-1:8540
    restart: unless-stopped

  witness-2:
    hostname: og-witness-2
    image: onegram-demo
    depends_on:
      - seed-node-1
    command: onegram_witness --witness-id '"1.6.2"' --seed-node seed-node-1:8540
    restart: unless-stopped

  witness-3:
    hostname: og-witness-3
    image: onegram-demo
    depends_on:
      - seed-node-1
    command: onegram_witness --witness-id '"1.6.3"' --seed-node seed-node-1:8540
    restart: unless-stopped

  witness-4:
    hostname: og-witness-4
    image: onegram-demo
    depends_on:
      - seed-node-1
    command: onegram_witness --witness-id '"1.6.4"' --seed-node seed-node-1:8540
    restart: unless-stopped

  witness-5:
    hostname: og-witness-5
    image: onegram-demo
    depends_on:
      - seed-node-1
    command: onegram_witness --witness-id '"1.6.5"' --seed-node seed-node-1:8540
    restart: unless-stopped

  witness-6:
    hostname: og-witness-6
    image: onegram-demo
    depends_on:
      - seed-node-1
    command: onegram_witness --witness-id '"1.6.6"' --seed-node seed-node-1:8540
    restart: unless-stopped

  witness-7:
    hostname: og-witness-7
    image: onegram-demo
    depends_on:
      - seed-node-1
    command: onegram_witness --witness-id '"1.6.7"' --seed-node seed-node-1:8540
    restart: unless-stopped

  witness-8:
    hostname: og-witness-8
    image: onegram-demo
    depends_on:
      - seed-node-1
    command: onegram_witness --witness-id '"1.6.8"' --seed-node seed-node-1:8540
    restart: unless-stopped

  witness-9:
    hostname: og-witness-9
    image: onegram-demo
    depends_on:
      - seed-node-1
    command: onegram_witness --witness-id '"1.6.9"' --seed-node seed-node-1:8540
    restart: unless-stopped

  witness-10:
    hostname: og-witness-10
    image: onegram-demo
    depends_on:
      - seed-node-1
    command: onegram_witness --witness-id '"1.6.10"' --seed-node seed-node-1:8540
    restart: unless-stopped

  witness-11:
    hostname: og-witness-11
    image: onegram-demo
    depends_on:
      - seed-node-1
    command: onegram_witness --witness-id '"1.6.11"' --seed-node seed-node-1:8540
    restart: unless-stopped

  portainer:
    hostname: portainer
    image: portainer/portainer
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - 9000:9000
